# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
          cache-dependency-path: subdir/go.sum

      - name: Verify dependencies
        run: go mod verify

      - name: Install dependencies
        run: |
          go get github.com/aws/aws-lambda-go
          go get github.com/awslabs/aws-lambda-go-api-proxy
          go get github.com/go-chi/chi/v5
          go get github.com/maragudk/gomponents
          go get github.com/maragudk/gomponents-heroicons
          go get github.com/matryer/is
          go get go.uber.org/zap
          go get golang.org/x/sync

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
